server:
  port: 9291

spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sshaunn/config-server
          clone-on-start: true
