server:
  port: 9291

spring:
  application:
    name: route
  cloud:
    gateway:
      routes:
        - id: EMPLOYEE-SERVICE
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employees/**

        - id: INCOME-SERVICE
          uri: lb://INCOME-SERVICE
          predicates:
            - Path=/calculate/**